### PR TITLE
Fix implementation of variable warpFactorLevel

### LINKED ISSUE #39: Maximum warp factor is hard-coded in warp.m, not changeable
https://github.com/dolphin-acoustics-vip/artwarp/blob/07925a077748ae4eb426d6e34d6b9666cc6277c5/warp.m#L19

The above code explicitly checks if the difference in lengths of two contours is greater than 3, rather than using the `warpFactorLevel` parameter as expected.

### LINKED ISSUE #67: Program crashes when warpFactorLevel is set to 2
Occasionally, when `ARTwarp_Run_Categorisation` is called and `warpFactorLevel` is set to 2, the program throws an error and crashes during categorisation. The error occurs when the condition on line 7 of `unwarp.m` is met and i=1, so when line 8 attempts to access `unwarpfun(i-1)`, no value for unwarpfun(0) exists (remembering MATLAB uses 1-based indexing). 

**Error message:**

Image

**Instructions to reproduce the error:**

- obtain example ctr files at: https://universityofstandrews907-my.sharepoint.com/:f:/g/personal/crdd_st-andrews_ac_uk/EtNRGptximhClEQA4WQQSyUBEbkEhNW9COXpLiHZu_bRuQ?e=1M7x0c
- save files to a folder named "ctr" in the same directory as the ARTwarp scripts
- run `ARTwarp_csv.m`
- File -> load frequency contours (*ctr) -> select folder "ctr"
- Analyse -> Run Categorisation -> set Warp Factor Level to 2 -> OK

### PR DESCRIPTION
**Pull request by KaiKerlaff**
Closes #39, Closes #67.

This is an attempt to fix the implementation of a variable `warpFactorLevel`, which was initially introduced in c5a395f but which did not correctly constrain the maximum warping factor to `warpFactorLevel` as intended. In the implementation of c5a395f, we found that when running the program with a `warpFactorLevel` of 2, the warping function produced (`warpfun`) still contained differences >2 between values at consecutive indexes, which indicates a compression warping factor greater than 2. 

I have tested this commit on a representative sample of 100 whistle contours provided by @RosieDay-Reader, with a `warpFactorLevel` of 2, 3, and 10, and have had no errors. For each run at a new `warpFactorLevel` I checked one random `warpfun` generated (one warping function of an active contour to a reference contour) and found it has contained (a) no more than `warpFactorLevel` equal values at consective indexes (indicating a correct constraint on the local expansion warping factor); and (b) differences no greater than `warpFactorLevel` between consecutive indexes (indicating a correct constraint on the local compression warping factor). However, I did not check that these conditions were met for every `warpfun` generated.

If anyone has advice on how to further test this new implementation (@vmjanik, @olexandr-konovalov, @RosieDay-Reader), I would greatly appreciate this.

### CODE REVIEW

**Review by vmjanik — APPROVED** [review]
As far as I can see, this looks good.

File: warp.m [hunk 1]
```diff
@@ -59,88 +59,67 @@
...
+            [y, x] = max([N(i-1,j+(r2(2:z))) NaN]); %AND the value stored at i-1,j is greater than warpFactorLevel, disqualify the vertical step (i.e choose only a diagonal or horizontal step)
+            p(i,j) = r2(x+1); % Update the path matrix to show the horizontal component of the step taken (i.e. -1, -2, ..., -warpFactorLevel)
+            k(i,j) = 1; % Reset the number of consecutive vertical steps to 1
         else
-            [y x] = max([N(i-1,j-1) N(i-1,j)]); %otherwise, the value of 'y' the maximum of N(i-1,j-1) OR N(i-1,j) and the value of 'x' is which of those two expressions is the largest (1 or 2)
+            [y, x] = max(N(i-1,j+(r2(1:z)))); %otherwise, choose the maximum previous value from any previous possible step (including the vertical)
+            if x == 1 % CHECK THIS IS CORRECT INDEXING OF above line - if the maximum previous value came from a vertical step:
+                k(i,j) = 1+k(i-1,j); % increment the number of consecutive vertical steps taken at k(i,j) from k(i-1,j)
+            else
+                k(i,j) = 1; % Otherwise, reset the number of consective vertical steps to 1
```
Comment (olexandr-konovalov) [inline warp.m:82]: typo "consective"

File: warp.m [hunk 2]
```diff
@@ -59,88 +59,67 @@
...
-                ks = 1 + k(i-1,j);
-            elseif y == N(i-1, j - 2)
-                x = 3;
-            elseif y == N(i-1, j -3)
-                x = 4;
+            [y, x] = max(N(i-1,j+r2));
+            if x == 1 % CHECK THIS IS CORRECT INDEXING OF above line - if the maximum previous value came from a vertical step:
+                k(i,j) = 1+k(i-1,j); % increment the number of consecutive vertical steps taken at k(i,j) from k(i-1,j)
+            else
+                k(i,j) = 1; % Otherwise, reset the number of consective vertical steps to 1
```
Comment (olexandr-konovalov) [inline warp.m:118]: typo "consective"

**Review by olexandr-konovalov — COMMENTED** [review]
@KaiKerlaff there are two typos - since this is already merged, you can use them next time as an example for "how to submit a PR" tutorial
